RWGuard:
  time_window: 5
  
  random_forest:
    n_estimators: 1000      
    criterion: "gini"       
    max_depth: null         
    min_samples_split: 2    
    min_samples_leaf: 1       
    max_features: "sqrt"     
    bootstrap: true
    class_weight: "balanced"
    random_state: 42
    n_jobs: -1

  naive_bayes:
    var_smoothing: 0.000000001      

  logistic_regression:
    max_iter: 5000
    C: 10.0             
    solver: "lbfgs"
    n_jobs: -1


ShieldFS:
  tiers: 1

  random_forest:
    n_estimators: 1000      
    criterion: "gini"       
    max_depth: null         
    min_samples_split: 2    
    min_samples_leaf: 1       
    max_features: "sqrt"     
    bootstrap: true
    class_weight: "balanced"
    random_state: 42
    n_jobs: -1

  naive_bayes:
    var_smoothing: 0.000000001      

  logistic_regression:
    max_iter: 5000
    C: 10.0           
    solver: "lbfgs"
    n_jobs: -1


Redemption:
  time_window: 2
  
  random_forest:
    n_estimators: 0
  naive_bayes:
    var_smoothing: 0    

  logistic_regression:
    max_iter: 0


CanCal:
  time_window: 5
  
  random_forest:
    n_estimators: 1000      
    criterion: "gini"       
    max_depth: null         
    min_samples_split: 2    
    min_samples_leaf: 1       
    max_features: "sqrt"     
    bootstrap: true
    class_weight: "balanced"
    random_state: 42
    n_jobs: -1

  naive_bayes:
    var_smoothing: 0.000000001      

  logistic_regression:
    max_iter: 5000
    C: 10.0           
    solver: "lbfgs"
    n_jobs: -1
